import pandas as pd


class ResearchLeadAgent:

    def combine(
        self,
        technical,
        predictions,
        risk,
        news,
        market_regime
    ):

        report = predictions.merge(
            technical,
            on="Ticker",
            how="left"
        )

        report = report.merge(
            risk,
            on="Ticker",
            how="left"
        )

        report = report.merge(
            news,
            on="Ticker",
            how="left"
        )

        # Market regime is the same for all stocks
        regime = market_regime["Regime"]

        report["Market_Regime"] = regime

        # -----------------------------
        # Convert signals
        # -----------------------------

        report["Technical_Signal"] = (
            report["Technical_Direction"]
            .map({
                "UP": 1,
                "DOWN": -1,
                "NEUTRAL": 0
            })
            .fillna(0)
        )

        report["Prediction_Signal"] = (
            report["UP_Probability"] * 2 - 1
        )

        report["News_Signal"] = (
            report["News_Sentiment"]
            .fillna(0)
        )

        # -----------------------------
        # Market regime adjustment
        # -----------------------------

        regime_adjustment = {
            "BULL": 0.10,
            "BEAR": -0.10,
            "SIDEWAYS": 0.0
        }

        report["Regime_Adjustment"] = (
            report["Market_Regime"]
            .map(regime_adjustment)
            .fillna(0)
        )

        # -----------------------------
        # Risk adjustment
        # -----------------------------

        report["Risk_Adjustment"] = (
            report["Risk_Level"]
            .map({
                "LOW": 0,
                "MEDIUM": -0.10,
                "HIGH": -0.20
            })
            .fillna(0)
        )

        # -----------------------------
        # Combined research score
        # -----------------------------

        report["Research_Score"] = (
            0.30 * report["Prediction_Signal"]
            + 0.25 * report["Technical_Signal"]
            + 0.20 * report["News_Signal"]
            + report["Regime_Adjustment"]
            + report["Risk_Adjustment"]
        )

        # -----------------------------
        # Final direction
        # -----------------------------

        def get_direction(score):

            if score > 0.20:
                return "UP"

            elif score < -0.20:
                return "DOWN"

            return "NEUTRAL"

        report["Final_Direction"] = (
            report["Research_Score"]
            .apply(get_direction)
        )

        return report


if __name__ == "__main__":

    technical = pd.read_csv(
        "data/processed/technical_agent_results.csv"
    )

    predictions = pd.read_csv(
        "data/processed/prediction_agent_results.csv"
    )

    risk = pd.read_csv(
        "data/processed/risk_agent_results.csv"
    )

    news = pd.read_csv(
        "data/processed/news_summary.csv"
    )

    # Temporary market regime result
    # generated by market_regime_agent.py
    from market_regime_agent import MarketRegimeAgent

    regime_agent = MarketRegimeAgent()

    market_data = regime_agent.get_market_data()

    market_regime = regime_agent.analyze(
        market_data
    )

    agent = ResearchLeadAgent()

    report = agent.combine(
        technical,
        predictions,
        risk,
        news,
        market_regime
    )

    columns = [
        "Ticker",
        "Date",
        "UP_Probability",
        "Technical_Direction",
        "News_Direction",
        "Market_Regime",
        "Risk_Level",
        "Research_Score",
        "Final_Direction"
    ]

    print("\nFINAL RESEARCH REPORT")
    print("=" * 110)

    print(
        report[columns].to_string(index=False)
    )

    report.to_csv(
        "data/processed/research_lead_report.csv",
        index=False
    )

    print("\nSaved:")
    print(
        "data/processed/research_lead_report.csv"
    )